#!/bin/bash

#Run commands in several hosts
#automatic packaging test
#automatic packaging test2
if [[ "$@" == "" ]]; then echo "no param!!" ;exit 1;fi;
CMD="$@"
HOSTS=$(cat ~/hostlist| grep -v ^#)


for i in $HOSTS;
do

        echo "##########################";
        echo Running $i;
        ssh  $i $CMD;
        echo Done;
        echo;
	echo;

done;

echo "CMD_Finished"
