#!/bin/bash

Files="temp.sh"
Target_dir='/root'
HOSTS=$(cat ~/hostlist| grep -v ^#)

#Generates the file
cat << EOT > ~/$Files

cat << EOL >> tt
echo "Hello"
EOL


EOT



for i in $HOSTS;
do

        echo "##########################";
        echo $i;
        scp  ~/$Files $i:$Target_dir;
	ssh $i bash ${Target_dir}/${Files}
        echo Done;
        echo;
	echo;

done;

echo "CMD_Finished"
