#!/bin/bash

#Run commands in several hosts
#automatic packaging test
#automatic packaging test2

HOSTS=$(cat ~/hostlist| grep -v ^#)


for i in $HOSTS;
do

        echo "##########################";
        echo Running $i;
        ssh-copy-id  $i;
        echo Done;
        echo;
	echo;

done;

echo "CMD_Finished"
