#!/bin/bash

Files=$1
Target_dir=$2
HOSTS=$(cat ~/hostlist | grep -v ^#)


for i in $HOSTS;
do

        echo "##########################";
        echo Running $i;
        scp -r $Files $i:$Target_dir;
        echo Done;
        echo;
	echo;

done;

echo "CMD_Finished"
