#!/bin/bash

##Global variables
TERM=$(tty)

Scp_run() {
##########
# $@ : remote host
# usage 
#	# Scp_run 192.168.0.11 192.168.0.12

local RANDOM_FILE=''
local RANDOM_FILE=lab_$RANDOM

cat << EOT > $RANDOM_FILE
##########
##########
#Put your script here

echo "remote run test2" > /root/test1

#The end of Script
##########
EOT
chmod 755 $RANDOM_FILE


for host in "$@"
do
        scp $RANDOM_FILE ${host}:~/
        ssh $host ./$RANDOM_FILE
        ssh $host rm -f ./$RANDOM_FILE
done

rm -f $RANDOM_FILE

}

Check_parameter() {

#Check parameter
if [[ $1 == "" ]]
then
	echo "No repository ip address"
	exit 1;
fi

}

Debug () {
	echo _Debug_CMD:$(date +%y%m%d_%H:%M:%S): "$@"
	echo OUTPUT-Started:
	"$@"
	echo OUTPUT-Done
}

Debug_print () {
	#Only print Command and no results. It will be used commands which include terminator such as ;, >, ||
	# Use single quote in Single quote
	# e.g. Debug_print $'echo \'ls -al\' | grep tt '

	echo _Debug_CMD:$(date +%y%m%d_%H:%M:%S): "$@"
}
